global:
  scrape_interval: 5s # Scrape every 5 seconds for fast testing

scrape_configs:
  - job_name: 'pspf-inventory'
    static_configs:
      - targets: ['host.docker.internal:8000']
  
  - job_name: 'pspf-courier'
    static_configs:
      - targets: ['host.docker.internal:8001']
      
  - job_name: 'pspf-fraud'
    static_configs:
      - targets: ['host.docker.internal:8002']